/**
 * @description       : 
 * @author            : Diky Nurosid
 * @group             : 
 * @last modified on  : 12-23-2021
 * @last modified by  : Diky Nurosid
**/
global class Schedule_TrialLink implements Schedulable{

	global void execute(SchedulableContext sc) {
       //   TrialLinkServices trialLinkServicesObject = new TrialLinkServices();
      //    trialLinkServicesObject.createTrialLinkConversionRecords();
     }
}